# Generated by Django 3.1.2 on 2021-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.CharField(max_length=19)),
            ],
        ),
    ]
