# Generated by Django 3.1.2 on 2021-02-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.TextField(null=True),
        ),
    ]
