# Generated by Django 3.1.2 on 2021-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_profilepic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profilepicture/')),
            ],
        ),
    ]
