# Generated by Django 3.1.2 on 2021-02-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_pic',
            new_name='profile_pic_model',
        ),
    ]
