# Generated by Django 3.1.2 on 2021-02-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
