# Generated by Django 3.1.2 on 2021-02-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_social_media_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
