# Generated by Django 3.1.2 on 2021-02-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
