# Generated by Django 3.1.2 on 2021-02-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_post_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilepic',
        ),
    ]
