# Generated by Django 3.1.2 on 2021-02-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_delete_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture_user', models.CharField(max_length=100)),
                ('user_profile_picture', models.ImageField(upload_to='profilepicture/')),
            ],
        ),
        migrations.DeleteModel(
            name='profile_pic_model',
        ),
    ]
