# Generated by Django 3.1.2 on 2021-03-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='message',
        ),
    ]
