# Generated by Django 3.1.2 on 2021-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20210316_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedbacks',
        ),
    ]
