# Generated by Django 3.1.2 on 2021-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_auto_20210316_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
