# Generated by Django 3.1.2 on 2021-04-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_contact_form_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_username',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
